### ISSUE TITLE
ARCO 203, TCN BRG NOT working

### ISSUE THREAD

**Issue by daviddcs** [132nd-vWing/ATRM#48] opened 2019-12-08 21:41 UTC
ARCO 203, TCN BRG NOT working.
Unsure if its a viper thing or not, but the BRG heading give's a wonky false positive. Is there another 49X in play?

(distance works ok)

**Comment by 132ndNeck** [comment] 2019-12-09 08:11
Copy, there should not be another 49X.
We should test if all other TACANs for the tankers work as intended.

During the next events, please spawn various tankers, and test their TACAN, and report in this thread which one is working, and which is not working:


**List:**

- AR 203: BUG

**Comment by 132ndNeck** [comment] 2019-12-16 15:27
Was a duplicate, recovery tanker at Nimitz had 49Y.

**Comment by 132ndNeck** [comment] 2019-12-16 15:32
Reported on another issue with several tacans that need updating, so closing this Issue as it have been identified and will be taken care of.

Thanks for reporting.

**Closed by 132ndNeck** 2019-12-16 15:32 UTC
Labels: NEED TESTING, bug
